### PR TITLE
Filing generic

### PR DESCRIPTION
**Pull request by generik0**
Hi @fir3pho3nixx 
Here is the failing example.
It is when i have a class with a generic and and an interface with the same generic.
Then ctor inject the interface with the generic resolved.
Castle can handel is no problem. But your resolver is not happy about it. specifically the HasMatchingGenericTypesWithoutArguments

within the FrameworkConfigurationDependencyResolver

Should the code not look more like this. i.e. it is only the serviceCollection itmes that should be checked :

image

return serviceCollection.Any(x => x.ServiceType == dependencyType) && dependencyType.IsGenericType && HasMatchingGenericTypeDefinitions(dependencyType);

### CODE REVIEW

**Comment by fir3pho3nixx** [comment]
Also did you notice the cheeky swap of [GetCallingAssembly](https://github.com/castleproject/Windsor/pull/392/files#diff-cfb755dae5d4b64badae2b0423e4ce04R49)? I think @jonorossi is right on this one. We have been waiting for this feature from netstandard1.6-. It totally borked log4net for a while.

**Comment by generik0** [comment]
@fir3pho3nixx Regarding  "GetCallingAssembly" i would recommend adding try catch to it.
Becasue GetEntryAssembly can cause an exceptionif there is no value entry.

**Comment by generik0** [comment]
@fir3pho3nixx How do we move on from here. Are you have a think, or do you need me to make any changes?

**Comment by fir3pho3nixx** [comment]
Nah mate. You are doing awesome. Sorry I have been non-responsive. There is actually a bigger problem here. We found that scopes with dual bound registrations were causing scoped lifestyles to behave as singletons. Fucking bizarre... let me gather the evidence and get back to you. Should be tomorrow night at this point.

**Comment by fir3pho3nixx** [comment]
My issue got bumped from MVC to the RAZOR team. 

https://github.com/aspnet/Mvc/issues/7540

Gutted.

**Comment by fir3pho3nixx** [comment]
Also just generally peeved about how this is going ...

**Comment by generik0** [comment]
@fir3pho3nixx 
I think we should focus on, that there is progress and we are learning a lot.
I have castle working with your last PR to master and cross wiring.

Just let me ask:
- are the scope lifestyle on views causing a leak, or is it ok?
- the cross wiring, is this causing any issues other than it doesn’t look nice?
- with the actions I made and your new implementations are there any issues other than it not looking nice?

Regards Rik

**Comment by fir3pho3nixx** [comment]
> are the scope lifestyle on views causing a leak, or is it ok?

I am not sure. I think @Inject support is causing a memory leak. I will run some JetBrains profiling over it to find it. For now I have the public API working on PR: https://github.com/fir3pho3nixx/Windsor.AspNetCore/pull/5

> the cross wiring, is this causing any issues other than it doesn’t look nice?

The memory leak we know about and I have changed this to use the component registration API. Please see [this](https://github.com/fir3pho3nixx/Windsor.AspNetCore/blob/aspnet-core-windsor-final/WebApp/Startup.cs#L75) as an example. What do think?

> with the actions I made and your new implementations are there any issues other than it not looking nice?

Yes. Most definitely. We have a memory leak, I am also not happy about the performance. I want this to run in a docker container without chewing up 1GB of memory. Not sure what your hosting requirements are but if this operates at 300MB I will be happy.

**Comment by fir3pho3nixx** [comment]
Can you re-raise this PR to target the https://github.com/fir3pho3nixx/Windsor.AspNetCore/tree/generic-problem branch?

It would help me not pollute master and understand the generic's problem better.

I would like to merge it with https://github.com/fir3pho3nixx/Windsor.AspNetCore/pull/5

**Comment by generik0** [comment]
Yes I will do it ASAP. I will clean up a little bit. Could you make a branch for it I can merge too?
Would you like the test classes and case in a special folder within the test project?

**Comment by generik0** [comment]
Just so you know I am still running on your old implementation. The implementation where you had castle actions in both the startup/configuration and configure.

**Comment by fir3pho3nixx** [comment]
Yes, we had to revert to the old version. I was gutted when controllers started behaving as singletons. I do believe I have fixed all the problems now. I am seeing memory level off at 150MB with a throughput of 250+ requests/second. 

I have made you a collaborator, so you should be able to create branches on both this repo and my Windsor fork. Let me know if you are still having trouble.

**Comment by fir3pho3nixx** [comment]
The last remaining things for this now: 

 - Fix `potential` generics problem. I reworked this to be a bit better and covered it with more tests. 
 - Create `options` API for defining lifestyle configurations so users can optionally change how TagHelpers, ViewComponents or Controllers are instantiated(Singleton, Scoped, Transient).
 - Update documentation, we need to explain the new CrossWire extension.

**Pull request closed without merging**
